basePath: /
definitions:
  response.Response:
    properties:
      code:
        description: code 7 failed 0 success. 7失败 0成功
        type: integer
      data:
        description: data. 结果数据
      msg:
        description: message. 消息
        type: string
    type: object
  seamlessWallet.AuthReq:
    properties:
      providerId:
        description: 通用参数 提供商id
        example: HZ
        type: string
      sign:
        description: 通用参数 签名
        example: c8687876a15b93d1251c124dbe1837a6
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      token:
        description: 通用参数 运营商在OpenGame中提供的token
        example: "123456"
        type: string
    type: object
  seamlessWallet.BalanceReq:
    properties:
      playerName:
        description: 玩家名称
        example: test
        type: string
      providerId:
        description: 通用参数 提供商id
        example: HZ
        type: string
      sign:
        description: 通用参数 签名
        example: c8687876a15b93d1251c124dbe1837a6
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      token:
        description: 通用参数 运营商在OpenGame中提供的token
        example: "123456"
        type: string
    type: object
  seamlessWallet.BetAck:
    properties:
      agentTxid:
        description: 运营商交易id
        example: tx2
        type: string
      currency:
        description: 货币类型
        example: USD
        type: string
      playerBalance:
        description: 玩家余额(扣款后)
        example: 800.85
        type: number
    type: object
  seamlessWallet.BetReq:
    properties:
      betAmount:
        description: 下注总金额
        example: 10
        type: number
      currency:
        description: 货币类型
        example: USD
        type: string
      gameId:
        description: 游戏id
        example: 1
        type: integer
      playerName:
        description: 玩家在运营商系统中的唯一标识
        example: test
        type: string
      providerId:
        description: 通用参数 提供商id
        example: HZ
        type: string
      sign:
        description: 通用参数 签名
        example: c8687876a15b93d1251c124dbe1837a6
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      token:
        description: 通用参数 运营商在OpenGame中提供的token
        example: "123456"
        type: string
      transactionId:
        description: 供应商交易id
        example: tx1
        type: string
      updatedTime:
        description: 更新时间戳
        example: 1234567890123
        type: integer
    type: object
  seamlessWallet.CloseGameParams:
    properties:
      agent:
        description: 通用参数 运营商id
        example: test
        type: string
      playerName:
        description: 玩家在运营商系统中的唯一标识
        example: test
        type: string
      sign:
        description: 通用参数 签名
        example: c623f86755262355f3b948ba96ae705e
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
    type: object
  seamlessWallet.GameListParams:
    properties:
      agent:
        description: 通用参数 运营商id
        example: test
        type: string
      language:
        description: 语言
        example: en
        type: string
      sign:
        description: 通用参数 签名
        example: c623f86755262355f3b948ba96ae705e
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
    type: object
  seamlessWallet.GameListRes:
    properties:
      demoAvailable:
        description: 试玩模式是否可用
        type: boolean
      gameId:
        description: 游戏id
        type: string
      icon:
        description: 游戏图标
        type: string
      name:
        description: 游戏名称
        type: string
    type: object
  seamlessWallet.History:
    properties:
      agentTxid:
        description: 运营商交易id
        example: tx2
        type: string
      bet:
        description: 下注金额
        example: 10
        type: number
      currency:
        description: 货币类型
        example: USD
        type: string
      gameId:
        description: 游戏id
        example: 1
        type: integer
      playerAmount:
        description: 玩家余额(返奖后)
        example: 800.85
        type: number
      playerName:
        description: 玩家在运营商系统中的唯一标识
        example: test
        type: string
      status:
        description: 状态 1:InProgress 2:Completed 3:CompleteInProcess 9:Canceled 10:CancelInProcess
        example: 1
        type: integer
      transactionId:
        description: 供应商交易id
        example: tx1
        type: string
      winAmount:
        description: 赢得金额
        example: 1
        type: number
    type: object
  seamlessWallet.HistoryListParams:
    properties:
      agent:
        description: 通用参数 运营商id
        example: test
        type: string
      date:
        description: 日期
        example: "2020-01-01"
        type: string
      gameId:
        description: 游戏id
        example: 1
        type: integer
      page:
        description: 页码
        example: 1
        type: integer
      playerName:
        description: 玩家在运营商系统中的唯一标识
        example: test
        type: string
      sign:
        description: 通用参数 签名
        example: c623f86755262355f3b948ba96ae705e
        type: string
      size:
        description: 每页条数 最大100
        example: 10
        type: integer
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      transactionId:
        description: 供应商交易id
        example: tx1
        type: string
    type: object
  seamlessWallet.OpenGameParams:
    properties:
      agent:
        description: 通用参数 运营商id
        example: test
        type: string
      cashierUrl:
        description: 破产之后弹出的充值⻚⾯
        example: https://www.google.com
        type: string
      currency:
        description: 货币类型 USD
        example: USD
        type: string
      demo:
        description: 是否为试玩模式
        type: boolean
      gameId:
        description: 游戏id
        example: "1"
        type: string
      language:
        description: 语言 en
        example: en
        type: string
      lobbyUrl:
        description: 返回按钮的对应连接
        example: https://www.google.com
        type: string
      sign:
        description: 通用参数 签名
        example: c623f86755262355f3b948ba96ae705e
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      token:
        description: 由运营商提供的token，⽤于在Authenticate⾥ 进⾏验证
        example: test_token
        type: string
    type: object
  seamlessWallet.PlayerAmount:
    properties:
      currency:
        description: 货币
        example: USD
        type: string
      playerBalance:
        description: 玩家余额
        example: 800.85
        type: number
      playerName:
        description: 玩家名称
        example: "1"
        type: string
    type: object
  seamlessWallet.RefundAck:
    properties:
      currency:
        description: AgentTxid string `json:"agentTxid" example:"tx3"` // 运营商内部的流水id
        example: USD
        type: string
      playerBalance:
        description: 玩家余额(退款后)
        example: 800.85
        type: number
    type: object
  seamlessWallet.RefundReq:
    properties:
      agentTxid:
        description: 运营商交易id
        example: tx3
        type: string
      betAmount:
        description: 下注总金额
        example: 10
        type: number
      gameId:
        description: 游戏id
        example: 1
        type: integer
      playerName:
        description: 玩家在运营商系统中的唯一标识
        example: test
        type: string
      providerId:
        description: 通用参数 提供商id
        example: HZ
        type: string
      sign:
        description: 通用参数 签名
        example: c8687876a15b93d1251c124dbe1837a6
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      token:
        description: 通用参数 运营商在OpenGame中提供的token
        example: "123456"
        type: string
      transactionId:
        description: 供应商交易id
        example: tx1
        type: string
      updatedTime:
        description: 更新时间戳
        example: 1234567890123
        type: integer
    type: object
  seamlessWallet.ResultAck:
    properties:
      agentTxid:
        description: 运营商交易id
        example: tx3
        type: string
      currency:
        description: 货币类型
        example: USD
        type: string
      playerBalance:
        description: 玩家余额(扣款后)
        example: 800.85
        type: number
    type: object
  seamlessWallet.ResultReq:
    properties:
      agentTxid:
        description: 运营商交易id
        example: tx2
        type: string
      betAmount:
        description: 下注总金额
        example: 10
        type: number
      currency:
        description: 货币类型
        example: USD
        type: string
      gameId:
        description: 机台id
        example: 1
        type: integer
      playerName:
        description: 玩家在运营商系统中的唯一标识
        example: test
        type: string
      providerId:
        description: 通用参数 提供商id
        example: HZ
        type: string
      sign:
        description: 通用参数 签名
        example: c8687876a15b93d1251c124dbe1837a6
        type: string
      timestamp:
        description: 通用参数 时间戳
        example: "1612345678000"
        type: string
      token:
        description: 通用参数 运营商在OpenGame中提供的token
        example: "123456"
        type: string
      transactionId:
        description: 供应商交易id
        example: tx1
        type: string
      updatedTime:
        description: 更新时间戳
        example: 1234567890123
        type: integer
      winAmount:
        description: 赢得金额
        example: 1
        type: number
    type: object
info:
  contact: {}
  title: API Document
  version: 0.0.1
paths:
  /seamless/authenticate:
    post:
      description: 打开游戏时，供应商将收到由娱乐场运营商生成的 URL 安全令牌。使用此令牌将要求娱乐场运营商进行玩家身份验证并获取玩家余额。
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.AuthReq'
      responses:
        "0":
          description: ""
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/seamlessWallet.PlayerAmount'
              type: object
      summary: Authenticate
      tags:
      - Seamless-Operator
  /seamless/balance:
    post:
      description: 通过此方法，供应商系统能知道玩家的当前余额并显示在游戏中
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.BalanceReq'
      responses:
        "0":
          description: ""
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/seamlessWallet.PlayerAmount'
              type: object
      summary: Balance
      tags:
      - Seamless-Operator
  /seamless/bet:
    post:
      description: |-
        此方法将会返回玩家的下注金额，运营商需确保玩家余额足够支付下注并扣除,如失败或异常请返回code 7
        余额不足时导致的错误可返回code 10，并需在data中携带playerBalance字段(此时玩家的真实余额)，客户端将依据此字段更新余额显示
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.BetReq'
      responses:
        "0":
          description: playerBalance为扣除下注后的余额
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/seamlessWallet.BetAck'
              type: object
      summary: Bet
      tags:
      - Seamless-Operator
  /seamless/closeGame:
    post:
      description: 关闭游戏
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.CloseGameParams'
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/response.Response'
      summary: CloseGame
      tags:
      - Seamless-Provider
  /seamless/gameList:
    post:
      description: 游戏列表
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.GameListParams'
      responses:
        "0":
          description: ""
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/seamlessWallet.GameListRes'
                  type: array
              type: object
      summary: GameList
      tags:
      - Seamless-Provider
  /seamless/historyList:
    post:
      description: 历史记录列表 playerName gameId transactionId date 为可选字段. status 1 玩家已开始游戏回合但尚未结束
        2 玩家已完成游戏回合 3 游戏回合在数据库中被标记为已完成；但是Result请求没有得到正确回复 9 游戏回合被游戏回合结束流程⾃动关闭 10退款处于异步队列中并正被发送给运营商
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.HistoryListParams'
      responses:
        "0":
          description: ""
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/seamlessWallet.History'
                  type: array
              type: object
      summary: HistoryList
      tags:
      - Seamless-Provider
  /seamless/openGame:
    post:
      description: 通过这种方法，运营商可以接收到所请求游戏的有效启动 URL。
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.OpenGameParams'
      responses:
        "0":
          description: URL将在data中返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: OpenGame
      tags:
      - Seamless-Provider
  /seamless/refund:
    post:
      description: 当收到退款请求时，运营商必须将钱退还给玩家 调用是幂等的，例如再次为现有投注发送退款只会创建一笔交易。此接口在失败时会定时重试,token字段为空。
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.RefundReq'
      responses:
        "0":
          description: ""
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/seamlessWallet.RefundAck'
              type: object
      summary: Refund
      tags:
      - Seamless-Operator
  /seamless/result:
    post:
      description: 此接口在失败时会定时重试,token字段为空，运营商需根据交易id保证在玩家赢得奖金时支付奖金的幂等性
      parameters:
      - description: 请求参数
        in: body
        name: RequestParams
        required: true
        schema:
          $ref: '#/definitions/seamlessWallet.ResultReq'
      responses:
        "0":
          description: ""
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/seamlessWallet.ResultAck'
              type: object
      summary: Result
      tags:
      - Seamless-Operator
swagger: "2.0"
tags:
- description: 供应商提供的的接口
  name: Seamless-Provider
- description: 运营商需实现的接口
  name: Seamless-Operator
