package business

type ServiceGroup struct {
	// Code generated by slot-server Begin; DO NOT EDIT.

	UserService
	SlotService
	SlotReelService
	SlotSymbolService
	SlotPayTableService
	SlotPaylineService
	JackpotService
	SlotTestsService
	ConfigsService
	SlotRecordService
	MoneyLogService
	SlotUserSpinService
	SlotEventService
	MoneyUserService
	SlotFakeService
	MoneySlotService
	MoneyUserSlotService
	SlotReelDataService
	MerchantService
	TrackingService
	ApiLogService
	DebugConfigService
	TxnService
	SlotFileUploadAndDownloadService
	TxnSubService
	CurrencyService
	SlotGenTplService
	SlotTemplateService
	SlotTemplateGenService
	// Code generated by slot-server End; DO NOT EDIT.
}
