package business

type RouterGroup struct {
	// Code generated by slot-server Begin; DO NOT EDIT.

	UserRouter
	SlotRouter
	SlotReelRouter
	SlotSymbolRouter
	SlotPayTableRouter
	SlotPaylineRouter
	JackpotRouter
	SlotTestsRouter
	ConfigsRouter
	SlotRecordRouter
	MoneyLogRouter
	SlotUserSpinRouter
	SlotEventRouter
	MoneyUserRouter
	SlotFakeRouter
	MoneySlotRouter
	MoneyUserSlotRouter
	SlotReelDataRouter
	MerchantRouter
	TrackingRouter
	ApiLogRouter
	DebugConfigRouter
	TxnRouter
	SlotFileUploadAndDownloadRouter
	TxnSubRouter
	CurrencyRouter
	SlotGenTplRouter
	SlotTemplateRouter
	SlotTemplateGenRouter
	// Code generated by slot-server End; DO NOT EDIT.
}
