package business

type ApiGroup struct {
	// Code generated by slot-server Begin; DO NOT EDIT.

	UserApi
	SlotApi
	SlotReelApi
	SlotSymbolApi
	SlotPayTableApi
	SlotPaylineApi
	JackpotApi
	SlotTestsApi
	ConfigsApi
	SlotRecordApi
	MoneyLogApi
	SlotUserSpinApi
	SlotEventApi
	MoneyUserApi
	SlotFakeApi
	MoneySlotApi
	MoneyUserSlotApi
	SlotReelDataApi
	MerchantApi
	TrackingApi
	ApiLogApi
	DebugConfigApi
	TxnApi
	SlotFileUploadAndDownloadApi
	TxnSubApi
	CurrencyApi
	SlotGenTplApi
	SlotTemplateApi
	SlotTemplateGenApi
	// Code generated by slot-server End; DO NOT EDIT.
}
