kind: pipeline
name: build
type: docker
volumes:
  - name: go-path
    host:
      path: /srv/go
  - name: go-cache
    host:
      path: /root/.cache/go-build

steps:
  - name: go-build
    image: golang:1.20.4
    commands:
      - cd ./slot-server
      - go mod tidy
      - go build
#      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
    volumes:
      - name: go-path
        path: /go
      - name: go-cache
        path: /root/.cache/go-build
    when:
      branch: [ dev, pre, prod ]

  - name: deploy-dev
    image: drillster/drone-rsync
    network_mode: host
    settings:
      hosts:
        - "172.18.0.1"
      port: 2220
      key:
        from_secret: ssh_password
      source: ./slot-server/*
      target: /srv/www/slot-server/
      include: [ "slot-server","config.docker.yaml","docker-compose.yaml","run.sh" ]
      exclude: [ "*" ]
      script:
        - export RUN_ENV=test
        - /srv/www/slot-server/run.sh "local:${type}"
    when:
      branch:
      - dev

  - name: deploy-pre-cluster
    image: drillster/drone-rsync
    network_mode: host
    settings:
      hosts:
        - "10.0.0.86"
        - "10.0.0.185"
      port: 2220
      key:
        from_secret: ssh_password
      source: ./slot-server/*
      target: /srv/slot-server/
      include: [ "slot-server","config.pre.yaml","docker-compose.yaml","run.sh" ]
      exclude: [ "*" ]
      script:
        - export RUN_ENV=pre
        - /srv/slot-server/run.sh "cluster:${type}"
    when:
      branch:
      - pre

  - name: deploy-pre-backend
    image: drillster/drone-rsync
    network_mode: host
    settings:
      hosts:
        - "10.0.0.36"
      port: 2220
      key:
        from_secret: ssh_password
      source: ./slot-server/*
      target: /srv/slot-server/
      include: [ "slot-server","config.pre.yaml","docker-compose.yaml","run.sh" ]
      exclude: [ "*" ]
      script:
        - export RUN_ENV=pre
        - /srv/slot-server/run.sh "backend:${type}"
    when:
      branch:
      - pre

  - name: deploy-prod-cluster
    image: drillster/drone-rsync
    network_mode: host
    settings:
      hosts:
        - "10.0.0.31"
        - "10.0.0.190"
      port: 2220
      key:
        from_secret: ssh_password
      source: ./slot-server/*
      target: /srv/slot-server/
      include: [ "slot-server","config.prod.yaml","docker-compose.yaml","run.sh" ]
      exclude: [ "*" ]
      script:
        - export RUN_ENV=prod
        - /srv/slot-server/run.sh "cluster:${type}"
    when:
      branch:
      - prod

  - name: deploy-prod-backend
    image: drillster/drone-rsync
    network_mode: host
    settings:
      hosts:
        - "10.0.0.121"
      port: 2220
      key:
        from_secret: ssh_password
      source: ./slot-server/*
      target: /srv/slot-server/
      include: [ "slot-server","config.prod.yaml","docker-compose.yaml","run.sh" ]
      exclude: [ "*" ]
      script:
        - export RUN_ENV=prod
        - /srv/slot-server/run.sh "backend:${type}"
    when:
      branch:
      - prod
