version: "3.3"
services:
  backend:
    image: ubuntu:latest
    container_name: slot-backend
    restart: always
    tty: true
    environment:
      - RUN_ENV=$RUN_ENV
    volumes:
      - ./:/srv/slot
      - /usr/share/zoneinfo:/usr/share/zoneinfo
    command: /srv/slot/slot-server -type=backend
    working_dir: /srv/slot
    network_mode: host
  master:
    image: ubuntu:latest
    container_name: slot-master
    restart: always
    environment:
      - RUN_ENV=$RUN_ENV
    tty: true
    volumes:
      - ./:/srv/slot
    command: /srv/slot/slot-server -type=master
    working_dir: /srv/slot
    network_mode: host
  gate:
    image: ubuntu:latest
    container_name: slot-gate
    restart: always
    environment:
      - RUN_ENV=$RUN_ENV
    tty: true
    volumes:
      - ./:/srv/slot
      - /usr/share/zoneinfo:/usr/share/zoneinfo
    command: /srv/slot/slot-server -type=gate
    working_dir: /srv/slot
    network_mode: host
  game:
    image: ubuntu:latest
    container_name: slot-game
    restart: always
    environment:
      - RUN_ENV=$RUN_ENV
    tty: true
    volumes:
      - ./:/srv/slot
      - /usr/share/zoneinfo:/usr/share/zoneinfo
    command: /srv/slot/slot-server -type=game
    working_dir: /srv/slot
    network_mode: host
  api:
    image: ubuntu:latest
    container_name: slot-api
    restart: always
    environment:
      - RUN_ENV=$RUN_ENV
    tty: true
    volumes:
      - ./:/srv/slot
      - /usr/share/zoneinfo:/usr/share/zoneinfo
    command: /srv/slot/slot-server -type=api
    working_dir: /srv/slot
    network_mode: host